const mongoose = require('mongoose');
const donorSchema=mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    address:{
        type:String
    },
    tel:{
        type:String
    },
    bloodgroup:{
        type:String
    },
    weight:{
        type:Number
    },
    date:{
        type:String
    },
    diseases:{
        type:String
    },
    age:{
        type:Number 
    },
    bloodPressure:{
        type:String
    },
    status:{
        type:Number,
        default:0
    }
})
module.exports = mongoose.model("Donor",donorSchema);